module.exports = {
  apps: [{
    name: 'vrc2link',
    script: 'server.js',
    instances: 1,
    exec_mode: 'fork',
    env: {
      PORT: process.env.PORT || '',
      API_KEY: process.env.API_KEY || '',
      BILIBILI_COOKIE: process.env.BILIBILI_COOKIE || '',
      NETEASE_COOKIE: process.env.NETEASE_COOKIE || '',
      DOUYIN_COOKIE: process.env.DOUYIN_COOKIE || '',
      KUAISHOU_COOKIE: process.env.KUAISHOU_COOKIE || '',
      SQLITE_PATH: process.env.SQLITE_PATH || '',
      CACHE_TTL_SECONDS: process.env.CACHE_TTL_SECONDS || '',
      RATE_LIMIT_ANON_PER_MINUTE: process.env.RATE_LIMIT_ANON_PER_MINUTE || '',
      RATE_LIMIT_AUTH_PER_MINUTE: process.env.RATE_LIMIT_AUTH_PER_MINUTE || '',
      RATE_LIMIT_IP_PER_MINUTE: process.env.RATE_LIMIT_IP_PER_MINUTE || '',
      RATE_LIMIT_WINDOW_SECONDS: process.env.RATE_LIMIT_WINDOW_SECONDS || '',
      DANMAKU_RATE_LIMIT_PER_MINUTE: process.env.DANMAKU_RATE_LIMIT_PER_MINUTE || '',
      DANMAKU_SESSION_TTL_SECONDS: process.env.DANMAKU_SESSION_TTL_SECONDS || '',
      DANMAKU_MAX_VIDEO_MESSAGES: process.env.DANMAKU_MAX_VIDEO_MESSAGES || '',
      DANMAKU_MAX_LIVE_MESSAGES: process.env.DANMAKU_MAX_LIVE_MESSAGES || '',
      TRUST_PROXY: process.env.TRUST_PROXY || '',
    },
    log_date_format: 'YYYY-MM-DD HH:mm:ss',
    error_file: './logs/error.log',
    out_file: './logs/out.log',
    merge_logs: true,
    max_memory_restart: '256M',
  }],
};
